#' Elastic net model used in the original muscle clock (MEAT).
#'
#' An object with S3 class "glmnet","elnet" generated by training 682
#' skeletal muscle DNA methylation profiles on a tranformed version of age.
#' This elastic net model can take in any skeletal muscle DNA methylation
#' profile that has been cleaned and calibrated to the GSE50498 gold standard
#' dataset, to estimate epigenetic age in the sample.
#'
#' @format An elastic net model
#' @seealso \code{\link[glmnet]{glmnet}}
"elasticnet_model_MEAT"
