// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scan_finite_unit_interval_cpp
void scan_finite_unit_interval_cpp(const arma::mat& x, std::string name, bool require_open);
RcppExport SEXP _bmiqpp_scan_finite_unit_interval_cpp(SEXP xSEXP, SEXP nameSEXP, SEXP require_openSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< bool >::type require_open(require_openSEXP);
    scan_finite_unit_interval_cpp(x, name, require_open);
    return R_NilValue;
END_RCPP
}
// beta_est_newton_cpp
Rcpp::List beta_est_newton_cpp(const arma::vec& y, const arma::vec& responsibility, const arma::vec& observation_weight, int maxit, int max_halving, double score_tol, double min_shape, double armijo);
RcppExport SEXP _bmiqpp_beta_est_newton_cpp(SEXP ySEXP, SEXP responsibilitySEXP, SEXP observation_weightSEXP, SEXP maxitSEXP, SEXP max_halvingSEXP, SEXP score_tolSEXP, SEXP min_shapeSEXP, SEXP armijoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type responsibility(responsibilitySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type observation_weight(observation_weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type max_halving(max_halvingSEXP);
    Rcpp::traits::input_parameter< double >::type score_tol(score_tolSEXP);
    Rcpp::traits::input_parameter< double >::type min_shape(min_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type armijo(armijoSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_est_newton_cpp(y, responsibility, observation_weight, maxit, max_halving, score_tol, min_shape, armijo));
    return rcpp_result_gen;
END_RCPP
}
// beta_mixture_em_cpp
Rcpp::List beta_mixture_em_cpp(const arma::vec& y, const arma::mat& initial_responsibility, int nL, Rcpp::Nullable<Rcpp::NumericVector> weights, int maxiter, double tol, int beta_maxit, int beta_max_halving, double beta_score_tol, double min_shape, double armijo, bool debug);
RcppExport SEXP _bmiqpp_beta_mixture_em_cpp(SEXP ySEXP, SEXP initial_responsibilitySEXP, SEXP nLSEXP, SEXP weightsSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP beta_maxitSEXP, SEXP beta_max_halvingSEXP, SEXP beta_score_tolSEXP, SEXP min_shapeSEXP, SEXP armijoSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_responsibility(initial_responsibilitySEXP);
    Rcpp::traits::input_parameter< int >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type beta_maxit(beta_maxitSEXP);
    Rcpp::traits::input_parameter< int >::type beta_max_halving(beta_max_halvingSEXP);
    Rcpp::traits::input_parameter< double >::type beta_score_tol(beta_score_tolSEXP);
    Rcpp::traits::input_parameter< double >::type min_shape(min_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type armijo(armijoSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_mixture_em_cpp(y, initial_responsibility, nL, weights, maxiter, tol, beta_maxit, beta_max_halving, beta_score_tol, min_shape, armijo, debug));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bmiqpp_scan_finite_unit_interval_cpp", (DL_FUNC) &_bmiqpp_scan_finite_unit_interval_cpp, 3},
    {"_bmiqpp_beta_est_newton_cpp", (DL_FUNC) &_bmiqpp_beta_est_newton_cpp, 8},
    {"_bmiqpp_beta_mixture_em_cpp", (DL_FUNC) &_bmiqpp_beta_mixture_em_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_bmiqpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
